elizaos-plugins/registry

- index.json
add the ton connect plugin, more info: 
https://github.com/elizaos-plugins/registry/issues/19
> feat: add ton-connect plugin

- index.json
add the state of mika plugin, more info:
https://github.com/elizaos-plugins/registry/issues/22
> feat: add state of mika plugin

- index.json
Plugin Information
Plugin Name: plugin-vana
Repository: https://github.com/Bilirose/plugin-vana
Current Maintainer: @Bilirose
Request Type
I would like to be a maintainer for this plugin, and want to add plugin-vana to index.json.
Qualifications
Created and developed the original plugin-vana for ElizaOS
Transfer tokens from one address to another on Vana
Actively maintaining the codebase
I am committed to:
Maintaining and updating the plugin regularly
Responding to issues and pull requests
Following ElizaOS plugin development guidelines
Collaborating with the community
Additional Notes
I have joined the Discord server to coordinate further steps and discussions.
Please let me know what additional information or steps are needed to proceed with the maintainer role.
> feat: add plugin-vana

- index.json
**Plugin Name**: `plugin-mina`
**Repository**: https://github.com/lispking/plugin-mina
**Current Maintainer**: @lispking
I am eager to become a maintainer of this plugin. Additionally, I propose adding `plugin-mina` to index.json.
I am the [original creator](https://github.com/elizaOS/eliza/pull/2702) and developer of `plugin-mina` for ElizaOS.
I have implemented the following core functions within the plugin:
* Enable seamless transfer of MINA tokens between wallets.
* Facilitate the querying of wallet balances and portfolio values.
* Provide real - time tracking of token prices and valuations.
* Manage all wallet interactions with the Mina network.
* Implement a caching mechanism for token prices to optimize performance.
* Provide the functionality to obtain faucet tokens for testing …
> feat: add plugin-mina

- index.json
Plugin Information
Plugin Name: plugin-aithra-toolkit
Repository: https://github.com/Itheum/plugin-aithra-toolkit
Current Maintainers: @bucurdavid @newbreedofgeek @KaelVenn
> feat: add plugin-aithra-toolkit

- index.json
**Plugin Name**: `plugin-navi`
**Repository**: https://github.com/lispking/plugin-navi
**Current Maintainer**: @lispking
I am eager to become a maintainer of this plugin. Additionally, I propose adding `plugin-navi` to index.json.
> feat: support plugin-navi

- index.json
Requesting xmtp plugin to be managed by https://github.com/ephemeraHQ/client-xmtp
Issue https://github.com/elizaos-plugins/registry/issues/36
> Update xmtp plugin

- index.json
> feat: add plugin-vara

- index.json
Fix https://github.com/elizaos-plugins/registry/issues/17
> feat: add eliza-plugin-rooch

- index.json
https://github.com/OrderlyNetwork/plugin-orderly
> feat: add orderly plugin

- index.json
> feat: add tako client

- site/index.html
Replace title with something suitable e.g. elizaOS Plugin Registry so I can easily this page from my open tabs 😅
> Update title in index.html

- index.json
> chore: add sqd plugin to registry

- index.json
Add plugin-sei to ElizaOS registry
> Add Plugin Sei to Registry

- index.json
This pull request adds in the Firecrawl plugin for Eliza that I built to the plugin registry. Would love a review from the maintainers and your thoughts on this.
Resolves #64
> feat: add firecrawl plugin

- index.json
https://github.com/elizaOS/eliza/pull/3565 
I'm submitting a PR that adds it to the registry as per the comments on this pull request. Thank you!
> add plugin merkle trade

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> feat: add gigbot plugin

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> feat: add plugin-multichain to plugin registry

- index.json
Add getPara Plugin 
- [docs](https://docs.getpara.com/welcome)
Registry:
```
plugin-name/
├── images/
├── src/
```
- Follow the …
> feat(registry): add getpara plugin

- index.json
> feat: add client tako

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> feat: add okto plugin

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> feat: add isaacx plugin

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> Add Flow Advanced Plugin

- index.json
added plugin-bnv-me-id
repo link: https://github.com/brand-new-vision/plugin-bnv-me-id
Registry:
```
plugin-name/
├── images/
├── src/
```
- Keep file sizes optimized (< 500KB for logos, < 1MB for …
> Add BNV ME:ID plugin

- index.json
add mbd farcaster plugin 
docs: http://mbd.xyz/
Registry:
```
plugin-name/
├── images/
├── src/
```
- Follow the [elizaOS Brand …
> add mbd farcaster plugin

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> added plugin computer use

- index.json
```
Plugin name: plugin-kaia
Repository: https://github.com/kaiachain/kaia-eliza-plugin
```
https://github.com/user-attachments/assets/08748e0b-ad6e-4ccb-8af4-f7fe1fbd4adb
Registry:
```
plugin-name/
├── images/
├── src/
```
- Use …
> Feat: Added Kaia Plugin

- index.json
Plugin repo: https://github.com/notorious-d-e-v/plugin-payai
Registry:
```
plugin-name/
├── images/
├── src/
```
- Follow the …
> feat: add PayAI Plugin

- index.json
Repo link: https://github.com/thopatevijay/plugin-sonic
Registry:
```
plugin-name/
├── images/
├── src/
```
- Follow the [elizaOS …
> adding plugin sonic

- index.json
Plugin name: plugin-siwe
Repository: https://github.com/DimaKush/plugin-siwe
Current Mainteiner: @DimaKush
I would like to be maintainer for this plugin
Created and developed the plugin-siwe for ElizaOS
Actively maintaining the codebase
Maintaining and updating the client/plugin repository
Responding to issues and pull requests
Following ElizaOS plugin development guidelines
Collaborating with the community
Registry:
```
plugin-name/
├── images/
├── src/
│   ├── adapters/ …
```
> addPluginSiwe

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> add client wechat

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> Add Enso to registry

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> feat: add client-clara

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> feat: add plugin-clara-twitter

- index.json
This pull request adds the DexPaprika plugin to the ElizaOS registry. DexPaprika is a comprehensive DeFi analytics API that provides real-time information about blockchain networks, decentralized exchanges (DEXes), liquidity pools, and tokens. This plugin enables ElizaOS users to access valuable crypto market data directly through their assistant.
The plugin implements 8 core actions to interact with the DexPaprika API:
- **GET_NETWORKS**: Retrieves all supported blockchain networks and their metadata
- **GET_NETWORK_DEXES**: Lists available DEXes on a specific network
- **GET_TOP_POOLS**: Gets top liquidity pools across all networks
- **GET_NETWORK_POOLS**: Provides top pools on a specific network
- **GET_DEX_POOLS**: Shows top pools on a specific DEX
- **GET_POOL_DETAILS**: Delivers …
> DexPaprika Plugin for ElizaOS Registry

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> feat: add plugin-storacha-storage

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> feat: add recall storage cot plugin

- index.json
Registry:
- ✔️I've made the organization @eliza-plugins
- ✔️I've used github not github.com
- ✔️ There is no .git extension
- ✔️It's placed it alphabetically in the list
- ✔️I've dealt with commas properly so the list is still valid JSON
- ✔️ is publically accessible (not a private repo)
- ✔️uses main as it's default branch
- ✔️I have include `elizaos-plugins` in the topics in the GitHub repo settings. If the plugin is related to `AI` or `crypto`, please add those as topics as well.
- ✔️ add simple description in github repo
- ✔️follows this convention
```
plugin-name/
├── images/
├── src/
│   ├── index.ts        # Main …
```
> Added plugin-xdc

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> feat: add rss3 plugin

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> feat: add membase plugin

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> feat: add zytron plugin

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> feat: add plugin-bnb

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> chore: add mcp plugin

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> Add Raiinmaker plugin to registry

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> Add Bless plugin to the registry

- index.json
This client is a fork of `client-twitter` and only uses the twitter API for authentication and performing actions.
Here is the repo for reference
https://github.com/notorious-d-e-v/client-twitter-api-access
Registry:
```
plugin-name/
├── images/
├── src/
└── README.md          # …
```
> feat: add client-twitter-api-access

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> plugin: Add XMTP to registry

- index.json
Adding plugin to registry as per @ChristopherTrimboli recommendation
Registry:
```
plugin-name/
├── images/
├── src/
```
- Follow …
> add plugin-morpheus

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> plugin-bitquery

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> add proof of agent plugin

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> Adds plugin pundiai dataset

- index.json
Registry:
```
plugin-name/
├── images/
├── src/
```
- …
> add reveel-payid plugin to registry

- scripts/generate-registry.js
**Problem:**
Plugin installation failures due to 404 errors when fetching from GitHub. Registry was storing cleaned versions (e.g., `1.0.0-beta.57`) but GitHub requires original tag names with `v` prefix (e.g., `v1.0.0-beta.57`).
**Solution:**
- Simplified tag processing logic to preserve original GitHub tag names
- Keep `v` prefixes in git version fields while still using cleaned versions for semver comparisons
- Fixes installation failures for plugins like discord, evm, node, redpill, etc.
**Testing:**
✅ Generated registry now contains `"version": "v1.0.0-beta.57"` instead of `"version": "1.0.0-beta.57"`
✅ GitHub URLs like `elizaos-plugins/plugin-discord#v1.0.0-beta.57` now resolve correctly
> fix: preserve GitHub tag v prefixes in registry generation

- generated-registry.json
Update plugins versions in registry json.
> chore: update plugins version

- generated-registry.json
> bump versions

- .github/workflows/generate-registry-json.yml
- scripts/generate-registry.js
This PR enhances the registry generation process to include additional repository metadata, making the registry more informative and useful for plugin discovery.
- New function: getGitHubRepoInfo - Fetches comprehensive repository metadata from GitHub API
- Enhanced data structure: Added the following fields to each registry entry:
- description: Repository description
- homepage: Project homepage URL
- topics: Repository topics/tags
- stargazers_count: GitHub star count
- language: Primary programming language
- Improved trigger conditions: Removed path filter restriction from GitHub workflow
- Broader automation: Workflow now triggers on all changes to main branch, not just index.json
1. Better Plugin Discovery: Users can now see repository descriptions, topics, and popularity metrics …
> feat: enhance registry with repository metadata

- generated-registry.json
- scripts/generate-registry.js
This PR fixes critical issues in the registry generation script related to v1 compatibility detection and semver handling.
- **Problem**: Packages were marked as v1-compatible based solely on having a v1.x version published, regardless of their `@elizaos/core` dependency
- **Example**: `@elizaos/plugin-hedera` was incorrectly marked as v1-compatible despite not having proper core dependency
- **Solution**: Enhanced NPM package inspection to fetch and validate actual `@elizaos/core` dependency ranges
- **Problem**: Raw dependency strings like `"latest"`, `"0.25.6-alpha.1"` caused `semver.satisfies()` to crash
- **Solution**: Added `normalizeDependencyRange()` and `safelyCheckSemverSatisfies()` helpers
✅ **Enhanced NPM package inspection**: Now extracts `@elizaos/core` dependency ranges …
> fix: improve v1 compatibility detection and prevent semver crashes
